exports.trans = {
    catch: {
        en: "catch %s",
        de: "catch %s",
        ru: "catch %s",
        pt: "catch %s",
        nl: "catch %s",
        fr: "catch %s",
        it: "catch %s",
        es: "catch %s",
        pl: "catch %s",
        uk: "catch %s",
        "zh-cn": "catch %s",
    },
    try: {
        en: "try %s",
        de: "try %s",
        ru: "try %s",
        pt: "try %s",
        nl: "try %s",
        fr: "try %s",
        it: "try %s",
        es: "try %s",
        pl: "try %s",
        uk: "try %s",
        "zh-cn": "try %s",
    },
    port_less: {
        en: "Port is automatically changed because it is less than 1025 - %s",
        de: "Port wird automatisch geändert, weil es weniger als 1025 ist - %s",
        ru: "Порт автоматически изменен, потому что он меньше 1025 - %s",
        pt: "O porto é automaticamente alterado porque é menos de 1025 - %s",
        nl: "Port is automatisch veranderd omdat het minder dan 1025 is - %s",
        fr: "Port est automatiquement changé parce qu'il est moins de 1025 - %s",
        it: "La porta viene cambiata automaticamente perché è inferiore a 1025 - %s",
        es: "El puerto se cambia automáticamente porque es menos de 1025 - %s",
        pl: "Port jest automatycznie zmieniany, ponieważ jest mniej niż 1025 - %s",
        uk: "Порт автоматично змінюється, оскільки він менше 1025 - %s",
        "zh-cn": "港口自动改变,因为它不到1025美元。 - %s",
    },
    port_greater: {
        en: "Port will be changed automatically as it is greater than 65535 - %s",
        de: "Port wird automatisch geändert, da es größer ist 65535 - %s",
        ru: "Порт будет изменен автоматически, поскольку он больше 65535 - %s",
        pt: "O porto será alterado automaticamente, pois é maior que 65535 - %s",
        nl: "Port zal automatisch veranderd worden als het groter is dan 65535 - %s",
        fr: "Port sera changé automatiquement car il est supérieur à 65535 - %s",
        it: "La porta sarà cambiata automaticamente in quanto è maggiore di 65535 - %s",
        es: "El puerto se cambiará automáticamente ya que es mayor que 65535 - %s",
        pl: "Port został zmieniony automatycznie, ponieważ jest ona większa niż 65535 - %s",
        uk: "Порт буде змінено автоматично, оскільки він більше 65535 - %s",
        "zh-cn": "港口将自动改变,因为这超过65535美元。 - %s",
    },
    port_use: {
        en: "Port %s is used!!",
        de: "Port %s wird verwendet!",
        ru: "Порт %s используется!",
        pt: "Port %s é usado!",
        nl: "Port %s is gebruikt!",
        fr: "Le port %s est utilisé !",
        it: "Port %s è usato!",
        es: "¡El puerto %s se utiliza!",
        pl: "Port %s jest używany!",
        uk: "Порт %s використовується!",
        "zh-cn": "使用第%s号港!",
    },
    enum_desc: {
        en: "List of the hiobs",
        de: "Liste der Hiobs",
        ru: "Список хобов",
        pt: "Lista dos hiobs",
        nl: "List van de hiob",
        fr: "Liste des hiobs",
        it: "Elenco degli hiobs",
        es: "Lista de los colobs",
        pl: "Lista Hiobs",
        uk: "Список юбів",
        "zh-cn": "黑客名单",
    },
    enum_name: {
        en: "HIOB",
        de: "HIOB",
        ru: "ГИОБ",
        pt: "HIOB",
        nl: "HIOB",
        fr: "HIOB",
        it: "HIOB",
        es: "HIOB",
        pl: "HIOB",
        uk: "HIOB",
        "zh-cn": "HIOB",
    },
    "Change common": {
        en: "Change common %s",
        de: "Change common %s",
        ru: "Change common %s",
        pt: "Change common %s",
        nl: "Change common %s",
        fr: "Change common %s",
        it: "Change common %s",
        es: "Change common %s",
        pl: "Change common %s",
        uk: "Change common %s",
        "zh-cn": "Change common %s",
    },
    create_enum: {
        en: "ENUM is created",
        de: "ENUM wird erstellt",
        ru: "ENUM создан",
        pt: "ENUM é criado",
        nl: "ENUM is gemaakt",
        fr: "ENUM est créé",
        it: "ENUM è creato",
        es: "ENUM es creado",
        pl: "ENUM została stworzona",
        uk: "ENUM створюється",
        "zh-cn": "成立森林论坛",
    },
    found_device: {
        en: "Devices %s found.",
        de: "Geräte %s gefunden.",
        ru: "Найдено устройств %s.",
        pt: "Dispositivos %s encontrados.",
        nl: "Devices %s gevonden.",
        fr: "Appareils %s trouvés.",
        it: "Dispositivi %s trovati.",
        es: "Dispositivos %s encontrados.",
        pl: "Znaleziono go w %s roku.",
        uk: "Пристрої %s знайшли.",
        "zh-cn": "被发现 %s 人。.",
    },
    Error: {
        en: "Error %s",
        de: "Fehler %s",
        ru: "Ошибка %s",
        pt: "Erro %s",
        nl: "Error %s",
        fr: "Erreur %s",
        it: "Errore %s",
        es: "Error %s",
        pl: "Error %s",
        uk: "Про нас %s",
        "zh-cn": "Error %s",
    },
    websocket_closed: {
        en: "Websocket closed",
        de: "Websocket geschlossen",
        ru: "Websocket закрыто",
        pt: "Websocket fechado",
        nl: "Websocket",
        fr: "Websocket fermé",
        it: "Websocket chiuso",
        es: "Websocket cerrado",
        pl: "Strona internetowa zamknięta",
        uk: "Веб-сайт закритий",
        "zh-cn": "关闭的网站",
    },
    data_receive: {
        en: "Data from %s receive: %s",
        de: "Daten von %s erhalten: %s",
        ru: "Данные от %s получают: %s",
        pt: "Dados de %s recebem: %s",
        nl: "Data van %s ontvangt: %s",
        fr: "Les données de %s reçoivent: %s",
        it: "I dati da %s ricevono: %s",
        es: "Los datos de %s reciben: %s",
        pl: "Dane z %s: %s",
        uk: "Дані з %s отримують: %s",
        "zh-cn": "来自%s的数据: %s",
    },
    content_data: {
        en: "No content data found: %s",
        de: "Keine Inhaltsdaten gefunden: %s",
        ru: "Информация не найдена: %s",
        pt: "Nenhum dado de conteúdo encontrado: %s",
        nl: "Geen gegevens gevonden: %s",
        fr: "Aucune donnée de contenu trouvée: %s",
        it: "Nessun dato di contenuto trovato: %s",
        es: "No se han encontrado datos de contenido: %s",
        pl: "Dane nie są znane: %s",
        uk: "Не знайдено інформації про вміст: %s",
        "zh-cn": "未发现的内容数据: %s",
    },
    not_type: {
        en: "Type not found: %s",
        de: "Typ nicht gefunden: %s",
        ru: "Тип не найден: %s",
        pt: "Tipo não encontrado: %s",
        nl: "Type niet gevonden: %s",
        fr: "Type non trouvé: %s",
        it: "Tipo non trovato: %s",
        es: "Tipo no encontrado: %s",
        pl: "Nieznana wersja: %s",
        uk: "Не знайдено: %s",
        "zh-cn": "未发现的类型: %s",
    },
    create_adapter: {
        en: "Created by Adapter",
        de: "Erstellt von Adapter",
        ru: "Создано адаптером",
        pt: "Criado por Adapter",
        nl: "Vertaling:",
        fr: "Créé par Adaptateur",
        it: "Creato da Adattatore",
        es: "Creado por Adapter",
        pl: "Stworzone przez Adaptera",
        uk: "Створено адаптером",
        "zh-cn": "A. 阿帕特创造",
    },
    connect: {
        en: "Connection",
        de: "Verbindung",
        ru: "Контакт",
        pt: "Conexão",
        nl: "Verbinding",
        fr: "Connexion",
        it: "Connessione",
        es: "Conexión",
        pl: "Connection",
        uk: "Підключення",
        "zh-cn": "A. 驱逐",
    },
    name: {
        en: "Name",
        de: "Name",
        ru: "Имя",
        pt: "Nome",
        nl: "Naam",
        fr: "Nom",
        it: "Nome",
        es: "Nombre",
        pl: "Nazwa",
        uk: "Ім'я",
        "zh-cn": "姓名",
    },
    ID: {
        en: "ID",
        de: "ID",
        ru: "КОД",
        pt: "ID",
        nl: "ID",
        fr: "ID",
        it: "ID",
        es: "ID",
        pl: "ID",
        uk: "ІМ'Я",
        "zh-cn": "ID ID",
    },
    key: {
        en: "Key",
        de: "Schlüssel",
        ru: "Ключ",
        pt: "Chaveiro",
        nl: "Sleutel",
        fr: "Key",
        it: "Chiave",
        es: "Clave",
        pl: "Key",
        uk: "Головна",
        "zh-cn": "关键",
    },
    date: {
        en: "Date",
        de: "Datum",
        ru: "Дата",
        pt: "Data",
        nl: "Datum",
        fr: "Date",
        it: "Data",
        es: "Fecha",
        pl: "D",
        uk: "Дата",
        "zh-cn": "日期",
    },
    approved: {
        en: "Approved",
        de: "Genehmigt",
        ru: "Утверждено",
        pt: "Aprovado",
        nl: "Goedgekeurd",
        fr: "Postes approuvés",
        it: "Approvazione",
        es: "Aprobado",
        pl: "Approved",
        uk: "Затвердження",
        "zh-cn": "核准",
    },
    login_pw: {
        en: "Login without password",
        de: "Login ohne Passwort",
        ru: "Вход без пароля",
        pt: "Login sem senha",
        nl: "Login zonder wachtwoord",
        fr: "Connexion sans mot de passe",
        it: "Accedi senza password",
        es: "Iniciar sesión sin contraseña",
        pl: "Login bez hasła",
        uk: "Вхід без пароля",
        "zh-cn": "无密码",
    },
    iob_id: {
        en: "ioBroker ID",
        de: "ioBroker ID",
        ru: "ioBroker ID",
        pt: "iD do ioBroker",
        nl: "ioBroker iD",
        fr: "ioBroker ID",
        it: "ioBroker ID",
        es: "ioBroker ID",
        pl: "ioBroker ID",
        uk: "іоБрокер ID",
        "zh-cn": "卢旺达",
    },
    login_suc: {
        en: "IP login %s successful",
        de: "IP-Login %s erfolgreich",
        ru: "IP логин %s успешно",
        pt: "IP login %s sucesso",
        nl: "IP login %s succesvol",
        fr: "Connexion IP %s succès",
        it: "IP login %s successo",
        es: "Acceso IP %s exitoso",
        pl: "IP login %s udany",
        uk: "IP-адреса %s успішний",
        "zh-cn": "I. IP砍伐. %s",
    },
    send_to: {
        en: "Send to %s - MSG: %s",
        de: "Zu %s senden - MSG: %s",
        ru: "Отправить по %s - MSG: %s",
        pt: "Enviar para %s - MSG: %s",
        nl: "Verzenden naar %s - MSG: %s",
        fr: "Envoyer à %s - MSG: %s",
        it: "Invia a %s - MSG: %s",
        es: "Enviar a %s - MSG: %s",
        pl: "Przesyłać do %s - MSG: %s",
        uk: "Відправлення до %s - MSG: %s",
        "zh-cn": "附录%s - MSG: %s",
    },
    wrong_pw: {
        en: "(%s) - Login invalid! Incorrect password or username!",
        de: "(%s) - Anmelden ungültig! Falsches Passwort oder Benutzername!",
        ru: "(%s) - Вход недействителен! Неправильный пароль или имя пользователя!",
        pt: "(%s) - Inválido! Senha incorreta ou nome de usuário!",
        nl: "(%s) - Login invalide! Onjuist wachtwoord of gebruikersnaam!",
        fr: "(%s) - Je suis invalide ! Mot de passe incorrect ou nom d'utilisateur!",
        it: "(%s) - Login non valido! Password errata o nome utente!",
        es: "(%s) - ¡Accede inválido! contraseña incorrecta o nombre de usuario!",
        pl: "(%s) - Login invalid (ang.). Incorrect password or username (ang.)!",
        uk: "(%s) - Вхід недійсний! Введіть пароль або ім'я користувача!",
        "zh-cn": "(%s) - 损失 错误的密码或用户名称!",
    },
    set_approve: {
        en: "Please set datapoint %s on true",
        de: "Bitte setzen Sie den Datenpunkt %s auf true",
        ru: "Пожалуйста, установите данные точки %s на true",
        pt: "Por favor, defina datapoint %s em true",
        nl: "Zet datapoint %s op de ware plaats",
        fr: "S'il vous plaît définir datapoint %s sur true",
        it: "Si prega di impostare datapoint %s su true",
        es: "Por favor establezca el punto de datos %s sobre la verdad",
        pl: "Załóżmy, że dany punkt danych %s jest prawdziwy",
        uk: "Будь ласка, встановіть точку даних %s на true",
        "zh-cn": "请确定数据点%s",
    },
    key_invalid: {
        en: "(%s) - Your key is invalid",
        de: "(%s) - Ihr Schlüssel ist ungültig",
        ru: "(%s) - Ваш ключ недействителен",
        pt: "(%s) - Sua chave é inválida",
        nl: "(%s) - Je sleutel is ongeldig",
        fr: "(%s) - Votre clé est invalide",
        it: "(%s) - La tua chiave è invalida",
        es: "(%s) - Tu llave es inválida",
        pl: "(%s) - Jego klucz jest nieważny",
        uk: "(%s) - Ваш ключ недійсний",
        "zh-cn": "(%s) - 你的关键是无效的",
    },
    pw_missing: {
        en: "(%s) - Password is missing",
        de: "(%s) - Passwort fehlt",
        ru: "(%s) - Пароль отсутствует",
        pt: "(%s) - A senha está faltando",
        nl: "(%s) - Het wachtwoord ontbreekt",
        fr: "(%s) - Mot de passe manquant",
        it: "(%s) - La password manca",
        es: "(%s) - Falta la contraseña",
        pl: "(%s) - Brak Hasło",
        uk: "(%s) - Відсутній пароль",
        "zh-cn": "(%s) - 护照名称",
    },
    user_missing: {
        en: "(%s) - Username is missing.",
        de: "(%s) - Benutzername fehlt.",
        ru: "(%s) - Имя пользователя отсутствует.",
        pt: "(%s) - O nome de usuário está faltando.",
        nl: "(%s) - De gebruikersnaam wordt vermist.",
        fr: "(%s) - L'utilisateur a disparu.",
        it: "(%s) - Manca il nome utente.",
        es: "(%s) - Falta el nombre de usuario.",
        pl: "(%s) - Nazwisko nie jest znane.",
        uk: "(%s) - Ім'я користувача відсутні.",
        "zh-cn": "(%s) - 用户名称失踪。.",
    },
    login_error: {
        en: "(%s) - Unknown login error",
        de: "(%s) - Unbekannter Login-Fehler",
        ru: "(%s) - Неизвестная ошибка входа",
        pt: "(%s) - Erro de login desconhecido",
        nl: "(%s) - Onbekende login fout",
        fr: "(%s) - Erreur de connexion inconnue",
        it: "(%s) - Errore di login sconosciuto",
        es: "(%s) - Error de inicio de sesión desconocido",
        pl: "(%s) - Nieznany błąd logowania",
        uk: "(%s) - Невідомий логін",
        "zh-cn": "(%s) - 已知的错误",
    },
    state_change: {
        en: "state change: %s",
        de: "Zustandsänderung: %s",
        ru: "изменение состояния: %s",
        pt: "mudança de estado: %s",
        nl: "verandering: %s",
        fr: "changement d ' état: %s",
        it: "cambiamento di stato: %s",
        es: "cambio estatal: %s",
        pl: "zmianę: %s",
        uk: "зміна стану: %s",
        "zh-cn": "国家变化: %s",
    },
    state_delete: {
        en: "Datapoint %s was deleted.",
        de: "Datapoint %s wurde gelöscht.",
        ru: "Datapoint %s удалена.",
        pt: "Datapoint %s foi excluído.",
        nl: "Datapoint %s is gewist.",
        fr: "Datapoint %s a été supprimé.",
        it: "Datapoint %s è stato cancellato.",
        es: "Se suprimió el punto %s.",
        pl: "Zniszczono numer %s.",
        uk: "Datapoint %s було видалено.",
        "zh-cn": "数据点%s被删除。.",
    },
    no_exists: {
        en: "Datapoint %s does not exist",
        de: "Datapoint %s existiert nicht",
        ru: "Datapoint %s не существует",
        pt: "Datapoint %s não existe",
        nl: "Datapoint %s bestaat niet",
        fr: "Datapoint %s n'existe pas",
        it: "Datapoint %s non esiste",
        es: "Datapoint %s no existe",
        pl: "Datapoint %s nie istnieje",
        uk: "Точка даних %s не існує",
        "zh-cn": "数据点%s",
    },
    dp_subs: {
        en: "Datapoint %s subscribed!",
        de: "Datapoint %s abonniert!",
        ru: "Datapoint %s подписался!",
        pt: "Datapoint %s inscrito!",
        nl: "Datapoint %s ingeschreven!",
        fr: "Datapoint %s a souscrit !",
        it: "Datapoint %s sottoscritto!",
        es: "Datapoint %s suscrito!",
        pl: "Datapoint %s!",
        uk: "%s підписаний!",
        "zh-cn": "数据点%s!",
    },
    no_enums: {
        en: "enum.hiob not found!",
        de: "enum.hiob nicht gefunden!",
        ru: "enum.hiob не найден!",
        pt: "enum.hiob não encontrado!",
        nl: "hiob niet gevonden!",
        fr: "enum.hiob pas trouvé!",
        it: "enum.hiob non trovato!",
        es: "enum.hiob no encontrado!",
        pl: "nie znajdziesz!",
        uk: "enum.hiob не знайдено!",
        "zh-cn": "页: 1!",
    },
    wo_login: {
        en: "Request without login: %s",
        de: "Anfrage ohne Anmeldung: %s",
        ru: "Запрос без логина: %s",
        pt: "Pedido sem login: %s",
        nl: "Verzoek zonder login: %s",
        fr: "Demande sans login: %s",
        it: "Richiesta senza login: %s",
        es: "Solicitud sin login: %s",
        pl: "Request without login: %s",
        uk: "Запит без логіки: %s",
        "zh-cn": "无逻辑请求: %s",
    },
    all_enums: {
        en: "Loading all ENUMS",
        de: "Alle ENUMS laden",
        ru: "Загрузка всех ENUMS",
        pt: "Carregando todos os ENUMS",
        nl: "Laden alle ENUMS",
        fr: "Charger toutes les ENUMS",
        it: "Caricamento in corso",
        es: "Cargando todos los ENUMS",
        pl: "Łączy wszystkie ENUMS",
        uk: "Завантаження всіх ENUMS",
        "zh-cn": "调动所有中非支助处",
    },
    created_enum: {
        en: "New ENMU created: %s",
        de: "Neue ENMU erstellt: %s",
        ru: "Новый ENMU создан: %s",
        pt: "Novo ENMU criado: %s",
        nl: "Nieuwe ENMU creëerde: %s",
        fr: "New ENMU created: %s",
        it: "Nuovo ENMU creato: %s",
        es: "Nuevo ENMU creado: %s",
        pl: "Nowe ENMU stworzyło nową formę: %s",
        uk: "Створено новий ENMU: %s",
        "zh-cn": "新建的电联: %s",
    },
    new_member: {
        en: "New ENMU member: %s",
        de: "Neue ENMU-Mitglied: %s",
        ru: "Новый член ENMU: %s",
        pt: "Novo membro da ENMU: %s",
        nl: "Nieuw ENMU lid: %s",
        fr: "New ENMU member: %s",
        it: "Nuovo membro ENMU: %s",
        es: "Nuevo miembro de ENMU: %s",
        pl: "Członek ENMU: %s",
        uk: "Новий учасник ENMU: %s",
        "zh-cn": "新联盟成员: %s",
    },
    del_member: {
        en: "The member has been deleted: %s",
        de: "Das Mitglied wurde gelöscht: %s",
        ru: "Член был удален: %s",
        pt: "O membro foi excluído: %s",
        nl: "Het lid is gewist: %s",
        fr: "Le membre a été supprimé: %s",
        it: "Il membro è stato cancellato: %s",
        es: "El miembro ha sido eliminado: %s",
        pl: "Członek został usunięty: %s",
        uk: "Відшкодування учасників: %s",
        "zh-cn": "成员已被删除: %s",
    },
    unknown_member: {
        en: "An unknown member has been deleted: %s",
        de: "Ein unbekanntes Mitglied wurde gelöscht: %s",
        ru: "Неизвестный член был удален: %s",
        pt: "Um membro desconhecido foi excluído: %s",
        nl: "Een onbekend lid is gewist: %s",
        fr: "Un membre inconnu a été supprimé: %s",
        it: "Un membro sconosciuto è stato cancellato: %s",
        es: "Un miembro desconocido ha sido eliminado: %s",
        pl: "Nieznany członek został usunięty: %s",
        uk: "Невідомий учасник: %s",
        "zh-cn": "未知成员已被删除: %s",
    },
    enmu_del: {
        en: "ENMU has been deleted: %s",
        de: "ENMU wurde gelöscht: %s",
        ru: "ENMU был удален: %s",
        pt: "ENMU foi excluído: %s",
        nl: "ENMU is gewist: %s",
        fr: "L'ENMU a été supprimé : %s",
        it: "ENMU è stato cancellato: %s",
        es: "ENMU ha sido eliminado: %s",
        pl: "ENMU została usunięta: %s",
        uk: "ЕНМУ видалено: %s",
        "zh-cn": "ENMU已被删除: %s",
    },
    all_enmu_del: {
        en: "All ENMU has been deleted! Please restart your Adapter!!! - %s",
        de: "Alle ENMU wurden gelöscht! Bitte starten Sie Ihren Adapter neu! - %s",
        ru: "Все ENMU удалено! Пожалуйста, перезапустите ваш адаптер! - %s",
        pt: "Todos ENMU foi excluído! Por favor reinicie seu adaptador! - %s",
        nl: "Alle ENMU is gewist! Herstart alsjeblieft je Adapter! - %s",
        fr: "Tout l'ENMU a été supprimé ! Veuillez redémarrer votre adaptateur ! - %s",
        it: "Tutto ENMU è stato cancellato! Riavviare il vostro adattatore! - %s",
        es: "¡Todo ENMU ha sido eliminado! ¡Por favor reinicia tu Adaptador! - %s",
        pl: "Wszystkie ENMU zostały usunięte. Powracaj swojego towarzysza! - %s",
        uk: "Усе було видалено! Будь ласка, перезапустіть адаптер! - %s",
        "zh-cn": "所有ENMU都已删除! 请再接再厉。! - %s",
    },
    disconnected: {
        en: "Device %s is disconnected.",
        de: "Das Gerät %s ist getrennt.",
        ru: "Устройство %s отключено.",
        pt: "O dispositivo %s está desligado.",
        nl: "Device %s is afgebroken.",
        fr: "Le périphérique %s est déconnecté.",
        it: "Il dispositivo %s è scollegato.",
        es: "El dispositivo %s está desconectado.",
        pl: "Uruchomiono %s.",
        uk: "Пристрої %s відключені.",
        "zh-cn": "有%s人被断绝。.",
    },
    Request_no_found: {
        en: "Your request has not yet been implemented! - %s",
        de: "Ihre Anfrage wurde noch nicht umgesetzt! - %s",
        ru: "Ваш запрос еще не реализован! - %s",
        pt: "Seu pedido ainda não foi implementado! - %s",
        nl: "Uw verzoek is nog niet voltooid! - %s",
        fr: "Votre demande n'a pas encore été mise en œuvre! - %s",
        it: "La vostra richiesta non è ancora stata implementata! - %s",
        es: "¡Tu solicitud aún no ha sido implementada! - %s",
        pl: "Zmiana nie została jeszcze wdrożona! - %s",
        uk: "Ваш запит ще не реалізований! - %s",
        "zh-cn": "你的要求尚未得到执行! - %s",
    },
    settings: {
        en: "Settings",
        de: "Einstellungen",
        ru: "Настройки",
        pt: "Configurações",
        nl: "Setting",
        fr: "Réglages",
        it: "Impostazioni impostazioni",
        es: "Ajustes",
        pl: "Setting",
        uk: "Налаштування",
        "zh-cn": "确定",
    },
    devices: {
        en: "Devices",
        de: "Geräte",
        ru: "Устройства",
        pt: "Dispositivos",
        nl: "Vernietiging",
        fr: "Appareils",
        it: "Dispositivi",
        es: "Dispositivos",
        pl: "Device",
        uk: "Пристрої",
        "zh-cn": "证人",
    },
    widgets: {
        en: "Widgets",
        de: "Widgets",
        ru: "Виджеты",
        pt: "Widgets",
        nl: "Widgets",
        fr: "Widgets",
        it: "Widgets",
        es: "Widgets",
        pl: "Widget",
        uk: "Віджети",
        "zh-cn": "目标",
    },
    screens: {
        en: "Screens",
        de: "Bildschirme",
        ru: "Экраны",
        pt: "Telas",
        nl: "Screens",
        fr: "Écrans",
        it: "Schermi",
        es: "Pantallas",
        pl: "Ekran",
        uk: "Екрани",
        "zh-cn": "筛选",
    },
    restarted: {
        en: "Websocket is restarted",
        de: "Websocket wird neu gestartet",
        ru: "Websocket перезапускается",
        pt: "Websocket é reiniciado",
        nl: "Websocket is herstart",
        fr: "Websocket est redémarré",
        it: "Websocket è riavviata",
        es: "Websocket está reiniciado",
        pl: "Wskaźnik internetowy jest restartowany",
        uk: "Websocket перезавантажити",
        "zh-cn": "网址",
    },
    ping_client: {
        en: "Send ping to client",
        de: "Ping an den Kunden senden",
        ru: "Отправить пинг клиенту",
        pt: "Enviar ping para o cliente",
        nl: "Stuur ping naar cliënt",
        fr: "Envoyer ping au client",
        it: "Inviare ping al cliente",
        es: "Enviar ping al cliente",
        pl: "Pozwólcie ping dla klienta",
        uk: "Надіслати запит",
        "zh-cn": "客户简历",
    },
    replied_client: {
        en: "Client replied",
        de: "Kunde antwortete",
        ru: "Клиент ответил",
        pt: "Cliente respondeu",
        nl: "Cliënt antwoordde",
        fr: "Client replied",
        it: "Il cliente ha risposto",
        es: "Cliente respondió",
        pl: "Client odpowiedział:",
        uk: "Клієнт відповів",
        "zh-cn": "客户答复",
    },
    check_client: {
        en: "Client checks",
        de: "Kundenüberprüfungen",
        ru: "Проверка клиентов",
        pt: "Verificações de clientes",
        nl: "Cliënt checks",
        fr: "Vérifications client",
        it: "Controllo clienti",
        es: "Comprobaciones de clientes",
        pl: "Klient check",
        uk: "Перевірка клієнтів",
        "zh-cn": "客户检查",
    },
};
